#!/usr/bin/env bash
# This script displays the content of /etc/passwd with additional information using the while loop and IFS

while IFS=':' read -r username _ userid groupid _ home shell; do
    user_info=$(awk -F ':' -v user="$username" '$1 == user {print $5}' /etc/passwd)
    echo "The user $username is part of the $groupid gang, lives in $home, and rides $shell."
    echo "User ID's place is protected by the passcode $username, more info about the user here: $userid INFO"
    echo
done < /etc/passwd
