#!/usr/bin/env bash
# This script displays time from 0 to 12 hours and 1 to 59 minutes

hours=0
minutes=1

while [ $hours -le 12 ]; do
  printf "Hour: %02d\n" $hours
  while [ $minutes -le 59 ]; do
    printf "%02d\n" $minutes
    minutes=$((minutes+1))
  done
  minutes=1
  hours=$((hours+1))
done | head -n 70
