#!/usr/bin/env bash
# This script displays time for 12 hours and 59 minutes

hours=0
minutes=1

while [ $hours -le 12 ]; do
  while [ $minutes -le 59 ]; do
    printf "%02d:%02d\n" $hours $minutes
    minutes=$((minutes+1))
    if [ $minutes -eq 60 ]; then
      hours=$((hours+1))
      minutes=0
    fi
    if [ $hours -eq 13 ]; then
      break 2
    fi
  done
done | head -n 70
