#!/usr/bin/env bash
#A new Bash scripts that creates and displays;

# Trap signals and define the corresponding actions
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit 0' SIGQUIT SIGTERM

# Write the PID to the file
echo $$ > /var/run/myscript.pid

# Display "To infinity and beyond" indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done
